spring:
  cloud:
    vault:
      kv:
        default-context:
        profile-separator: /
        backend: gallery
        enabled: true
      token: password
      scheme: http
      host: 192.168.1.200
      port: 8250
  config:
    import: vault://