spring:
  cloud:
    vault:
      kv:
        default-context:
        profile-separator: /
        backend: ${VAULT_BACKEND}
        enabled: true
      token: ${VAULT_TOKEN}
      scheme: ${VAULT_HTTP_SCHEME}
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      enabled: true
  config:
    import: vault://

  data:
    mongodb:
      database: gallery-management-docker