server:
  port: 80

spring:
  data:
    mongodb:
      database: gallery-management
      host: 192.168.1.200
      port: 27017
      requiresAuth: true
      username: steve
      password: password
      authenticationDatabase: admin

s3:
  baseUrl: http://baseUrl.example.com/