server:
  port: 8100

spring:
  application:
    name: gallery-management-service
  data:
    mongodb:
      applicationName: gallery-management-service
      database: gallery-management
      host: localhost
      port: 27017
      requiresAuth: false
      username:
      password:
      authenticationDatabase:
  mvc:
    servlet:
      path: /api

cloud:
  aws:
    s3:
      endpoint: http://192.168.1.200:9000
      bucketName: "gallery"
      region:
    credentials:
      accessKey: steve
      secretKey: password