server:
  port: 8101

spring:
  application:
    name: gallery-management-service
  data:
    mongodb:
      applicationName: gallery-management-service
      database: gallery-management-test
      host: localhost
      port: 27017
      requiresAuth: false
      username:
      password:
      authenticationDatabase:
  mvc:
    servlet:
      path: /api

s3:
  baseUrl: http://baseUrl.example.com/